natuur.default.gebiedid = 1
natuur.default.landid   = 1
natuur.default.rang     = le

natuur.lijst.columnheader.background    = #9BBB59
natuur.lijst.row.conditional.background = #E1EBCD
natuur.lijst.titel.background           = #9BBB59

natuur.regiolijst.taal.1  = nld
natuur.regiolijst.taal.2  = eng
natuur.regiolijst.taal.3  = fra

natuur.stylesheet = /common/css/Groen_app-4.0.0.css
