ALTER TABLE NATUUR.GEBIEDEN
	ADD COLUMN LATITUDE                        CHAR(1),
	ADD COLUMN LATITUDE_GRADEN                 NUMERIC(2),
	ADD COLUMN LATITUDE_MINUTEN                NUMERIC(2),
	ADD COLUMN LATITUDE_SECONDEN               NUMERIC(5,3),
	ADD COLUMN LONGITUDE                       CHAR(1),
	ADD COLUMN LONGITUDE_GRADEN                NUMERIC(3),
	ADD COLUMN LONGITUDE_MINUTEN               NUMERIC(2),
	ADD COLUMN LONGITUDE_SECONDEN              NUMERIC(5,3);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LATITUDE CHECK(LATITUDE = ANY (ARRAY['N'::bpchar, 'S'::bpchar]));

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LATITUDE_GRADEN CHECK(LATITUDE_GRADEN >= 0 AND LATITUDE_GRADEN < 90);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LATITUDE_MINUTEN CHECK(LATITUDE_MINUTEN >= 0 AND LATITUDE_MINUTEN < 60);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LATITUDE_SECONDEN CHECK(LATITUDE_SECONDEN >= 0 AND LATITUDE_SECONDEN < 60);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LONGITUDE CHECK(LONGITUDE = ANY (ARRAY['E'::bpchar, 'W'::bpchar]));

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LONGITUDE_GRADEN CHECK(LONGITUDE_GRADEN >= 0 AND LONGITUDE_GRADEN < 180);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LONGITUDE_MINUTEN CHECK(LONGITUDE_MINUTEN >= 0 AND LONGITUDE_MINUTEN < 60);

ALTER TABLE NATUUR.GEBIEDEN
  ADD CONSTRAINT CHK_GEB_LONGITUDE_SECONDEN CHECK(LONGITUDE_SECONDEN >= 0 AND LONGITUDE_SECONDEN < 60);

COMMENT ON COLUMN NATUUR.GEBIEDEN.LATITUDE            IS 'De latitude (N of S).';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LATITUDE_GRADEN     IS 'De latitude. Graden deel.';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LATITUDE_MINUTEN    IS 'De latitude. Minuten deel.';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LATITUDE_SECONDEN   IS 'De latitude. Seconden deel.';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LONGITUDE           IS 'De longitude (E of W)';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LONGITUDE_GRADEN    IS 'De longitude. Graden deel.';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LONGITUDE_MINUTEN   IS 'De longitude. Minuten deel.';
COMMENT ON COLUMN NATUUR.GEBIEDEN.LONGITUDE_SECONDEN  IS 'De longitude. Seconden deel.';

